### ISSUE TITLE
Question about updating the server using your method

### ISSUE THREAD

**Issue by NicciZar** [maxdelayer/DLUQuickstart#1]
Thank you for your install method.

I was wondering If there would be an easy way to update / rebuild the server?

-------

Also when first installing via your method using xubuntu the repo folders that were downloaded wouldnt be placed inside your DLU folder (just placed inside the home directory)  but moving them manually inside your DLU folder works fine!

**Comment by maxdelayer** [comment]
Thanks! It's great to hear someone has gotten use out of this. I've been meaning to update it since my initial release but I've been too busy with life to get around to committing some tweaks and otherwise cleaning up my code.

Re: easily updating/redeploying the server, I have ideas for this and it's definitely one of the things that's missing in my workflow that I want to fix. Right now it's wayyyyy too manual to rebuild and re-run the server when there are issues with it. Thanks for the reminder! I'll see about doing that sometime soon.

**Comment by maxdelayer** [comment]
This also reminds me: the big thing I did some tinkering with post initial commit was to successfully get the account creation system running in a more stable daemon. There is some residue from this in the repo currently but I need to clean up that workflow and automate it + add documentation for it as well. That's the current plan, alongside double checking for any updates DLU has made and adding a quick filter to modify the code to turn off the chat filter while still using DLU's repo.

**Comment by NicciZar** [comment]
Great to hear. Don't worry real life is more important!

If you update the script I could also set up a new VM (or for updating I'll copy mine) to see if it works

I'm not using any cloud hosting provider, I'm running it on my own Proxmox.

I was also tinkering with putting the starting script into the Linux autostart but I didn't get it to work so I have to connect to my VM and enter the script manually

**Comment by maxdelayer** [comment]
As always, took longer to get around to it than I hoped, but I did get a system like this up and running with the new `servermanager.sh` which vastly simplifies the running of the server. In it's current form it can turn off, turn on, or recompile the server with the corresponding option, and in the future I'll roll other things in so everything can be managed from one script.

Let me know if anything else comes up, if it doesn't work as expected, or you have other suggestions!
